[package]
name = "zegra"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.77"

[lib]
name = "zegra_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "zegra"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "blocking", "rustls"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = "2.11.5"
thiserror = "2.0.19"
walkdir = "2.5.0"

[build-dependencies]
tauri-build = "2.6.3"

[dev-dependencies]
tempfile = "3.27.0"
